"""empty message

Revision ID: 1ababc72c85f
Revises: 517750b97f9b
Create Date: 2020-12-20 19:18:46.806258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ababc72c85f'
down_revision = '517750b97f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
