"""empty message

Revision ID: 9fc1c9f4ce74
Revises: 1ababc72c85f
Create Date: 2020-12-22 15:20:09.125110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc1c9f4ce74'
down_revision = '1ababc72c85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
